### ISSUE TITLE
Screen blinks when a date clicked in "result list" view

### ISSUE THREAD

**Issue by meganetaaan** [hifive/hifive-test-library#17]
結果リスト画面である日付をクリックした際、ビュー全体にインジケータが表示されるが、
ごく短い時間でその表示が消えるために、画面が点滅したように見える。
この操作を繰り返すと目に優しくないので、インジケータの表示領域を狭めるなど改善してほしい。

**Comment by tkashi** [comment]
test-explorerのissueなので、そちらにissueを登録してください

**Comment by meganetaaan** [comment]
test-explorerのissueに登録しました。こちらは閉じていただけますか。
hifive/hifive-test-explorer#12
